### PR TITLE
Switch from deprecated Carbon Component API ...

### PR DESCRIPTION
**Pull request by sparkpunkd**
... to AudioUnit AudioComponent API.

Should work on SnowLeopard 10.6 onwards. Fixes issue #69

### CODE REVIEW

**Comment by fritx** [comment]
@sparkpunkd is this branch published on npm?

**Comment by LinusU** [comment]
Hi @sparkpunkd,

Sorry that this has gone unnoticed for such a long time. Do you think we should publish this a breaking version, or do we think that everyone already is on 10.6 and up and just push this as a patch release?

**Comment by sparkpunkd** [comment]
@fritx This pull request is not published to npm ... waiting on pull request acceptance. 

@LinusU I'm no expert, but a Google search tells me that in 2014, less than 2% of Macs are on 10.6 or earlier, which would suggest a patch release? See https://www.intego.com/mac-security-blog/os-x-market-share-statistics-1-in-5-macs-still-unsupported/

**Comment by LinusU** [comment]
Awesome! Again, sorry for the delay...

**Comment by LinusU** [comment]
(btw, the failing AppVeyor build seemed unrelated...)

**Comment by LinusU** [comment]
Published as `0.3.1`

**Pull request merged**
